version: '3.9'

services:
  web:
    build: .
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/gems
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
